# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure("2") do |config|
  # use the insecure key
  config.ssh.insert_key = false
  config.vm.box = "occs/centos7"

  config.vm.provider "virtualbox" do |vb|
     # Set the name of the box
     vb.name = "occs_centos7"

     # Don't display the VirtualBox GUI when booting the machine
     vb.gui = false

     # Customize the amount of memory on the VM:
     vb.memory = "1024"
  end

  # Override the /vagrant mount
  config.vm.synced_folder ".", "/vagrant", disabled: true

end
